spring:
  application:
    name: AuthorizationOAuthServer
  datasource:
    url: jdbc:mariadb://localhost:3306/oauth2
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
ldap:
  url: ldap://ldap.forumsys.com:389
  dn: cn=read-only-admin,dc=example,dc=com
  password: password
  base: dc=example,dc=com